// This file is @generated by wasmcloud/weld-codegen 0.6.0.
// It is not intended for manual editing.
// namespace: org.wasmcloud.interface.todo.todo

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    model::{U16, encode_u16, decode_u16},
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// map data structure for holding http headers
///
pub type HeaderMap = std::collections::HashMap<String, HeaderValues>;

// Encode HeaderMap as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_header_map<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &HeaderMap,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(val.len() as u64)?;
    for (k, v) in val {
        e.str(k)?;
        encode_header_values(e, v)?;
    }
    Ok(())
}

// Decode HeaderMap from cbor input stream
#[doc(hidden)]
pub fn decode_header_map(d: &mut wasmbus_rpc::cbor::Decoder<'_>) -> Result<HeaderMap, RpcError> {
    let __result = {
        {
            let map_len = d.fixed_map()? as usize;
            let mut m: std::collections::HashMap<String, HeaderValues> =
                std::collections::HashMap::with_capacity(map_len);
            for _ in 0..map_len {
                let k = d.str()?.to_string();
                let v = decode_header_values(d).map_err(|e| {
                    format!(
                        "decoding 'org.wasmcloud.interface.todo.todo#HeaderValues': {}",
                        e
                    )
                })?;
                m.insert(k, v);
            }
            m
        }
    };
    Ok(__result)
}
pub type HeaderValues = Vec<String>;

// Encode HeaderValues as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_header_values<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &HeaderValues,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(val.len() as u64)?;
    for item in val.iter() {
        e.str(item)?;
    }
    Ok(())
}

// Decode HeaderValues from cbor input stream
#[doc(hidden)]
pub fn decode_header_values(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<HeaderValues, RpcError> {
    let __result = {
        if let Some(n) = d.array()? {
            let mut arr: Vec<String> = Vec::with_capacity(n as usize);
            for _ in 0..(n as usize) {
                arr.push(d.str()?.to_string())
            }
            arr
        } else {
            // indefinite array
            let mut arr: Vec<String> = Vec::new();
            loop {
                match d.datatype() {
                    Err(_) => break,
                    Ok(wasmbus_rpc::cbor::Type::Break) => break,
                    Ok(_) => arr.push(d.str()?.to_string()),
                }
            }
            arr
        }
    };
    Ok(__result)
}
/// HttpRequest contains data sent to actor about the http request
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct HttpRequest {
    /// Request body as a byte array. May be empty.
    #[serde(with = "serde_bytes")]
    #[serde(default)]
    pub body: Vec<u8>,
    /// map of request headers (string key, string value)
    pub header: HeaderMap,
    /// HTTP method. One of: GET,POST,PUT,DELETE,HEAD,OPTIONS,CONNECT,PATCH,TRACE
    #[serde(default)]
    pub method: String,
    /// full request path
    #[serde(default)]
    pub path: String,
    /// query string. May be an empty string if there were no query parameters.
    #[serde(rename = "queryString")]
    #[serde(default)]
    pub query_string: String,
}

// Encode HttpRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_http_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &HttpRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(5)?;
    e.str("body")?;
    e.bytes(&val.body)?;
    e.str("header")?;
    encode_header_map(e, &val.header)?;
    e.str("method")?;
    e.str(&val.method)?;
    e.str("path")?;
    e.str(&val.path)?;
    e.str("queryString")?;
    e.str(&val.query_string)?;
    Ok(())
}

// Decode HttpRequest from cbor input stream
#[doc(hidden)]
pub fn decode_http_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<HttpRequest, RpcError> {
    let __result = {
        let mut body: Option<Vec<u8>> = None;
        let mut header: Option<HeaderMap> = None;
        let mut method: Option<String> = None;
        let mut path: Option<String> = None;
        let mut query_string: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct HttpRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => body = Some(d.bytes()?.to_vec()),
                    1 => {
                        header = Some(decode_header_map(d).map_err(|e| {
                            format!(
                                "decoding 'org.wasmcloud.interface.todo.todo#HeaderMap': {}",
                                e
                            )
                        })?)
                    }
                    2 => method = Some(d.str()?.to_string()),
                    3 => path = Some(d.str()?.to_string()),
                    4 => query_string = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "body" => body = Some(d.bytes()?.to_vec()),
                    "header" => {
                        header = Some(decode_header_map(d).map_err(|e| {
                            format!(
                                "decoding 'org.wasmcloud.interface.todo.todo#HeaderMap': {}",
                                e
                            )
                        })?)
                    }
                    "method" => method = Some(d.str()?.to_string()),
                    "path" => path = Some(d.str()?.to_string()),
                    "queryString" => query_string = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        HttpRequest {
            body: if let Some(__x) = body {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpRequest.body (#0)".to_string(),
                ));
            },

            header: if let Some(__x) = header {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpRequest.header (#1)".to_string(),
                ));
            },

            method: if let Some(__x) = method {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpRequest.method (#2)".to_string(),
                ));
            },

            path: if let Some(__x) = path {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpRequest.path (#3)".to_string(),
                ));
            },

            query_string: if let Some(__x) = query_string {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpRequest.query_string (#4)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// HttpResponse contains the actor's response to return to the http client
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct HttpResponse {
    /// Body of response as a byte array. May be an empty array.
    #[serde(with = "serde_bytes")]
    #[serde(default)]
    pub body: Vec<u8>,
    /// Map of headers (string keys, list of values)
    pub header: HeaderMap,
    /// statusCode is a three-digit number, usually in the range 100-599,
    /// A value of 200 indicates success.
    #[serde(rename = "statusCode")]
    pub status_code: U16,
}

// Encode HttpResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_http_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &HttpResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(3)?;
    e.str("body")?;
    e.bytes(&val.body)?;
    e.str("header")?;
    encode_header_map(e, &val.header)?;
    e.str("statusCode")?;
    encode_u16(e, &val.status_code)?;
    Ok(())
}

// Decode HttpResponse from cbor input stream
#[doc(hidden)]
pub fn decode_http_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<HttpResponse, RpcError> {
    let __result = {
        let mut body: Option<Vec<u8>> = None;
        let mut header: Option<HeaderMap> = None;
        let mut status_code: Option<U16> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct HttpResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => body = Some(d.bytes()?.to_vec()),
                    1 => {
                        header = Some(decode_header_map(d).map_err(|e| {
                            format!(
                                "decoding 'org.wasmcloud.interface.todo.todo#HeaderMap': {}",
                                e
                            )
                        })?)
                    }
                    2 => {
                        status_code = Some(decode_u16(d).map_err(|e| {
                            format!("decoding 'org.wasmcloud.interface.todo.todo#U16': {}", e)
                        })?)
                    }
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "body" => body = Some(d.bytes()?.to_vec()),
                    "header" => {
                        header = Some(decode_header_map(d).map_err(|e| {
                            format!(
                                "decoding 'org.wasmcloud.interface.todo.todo#HeaderMap': {}",
                                e
                            )
                        })?)
                    }
                    "statusCode" => {
                        status_code = Some(decode_u16(d).map_err(|e| {
                            format!("decoding 'org.wasmcloud.interface.todo.todo#U16': {}", e)
                        })?)
                    }
                    _ => d.skip()?,
                }
            }
        }
        HttpResponse {
            body: if let Some(__x) = body {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpResponse.body (#0)".to_string(),
                ));
            },

            header: if let Some(__x) = header {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpResponse.header (#1)".to_string(),
                ));
            },

            status_code: if let Some(__x) = status_code {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field HttpResponse.status_code (#2)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// Description of Todo service
/// wasmbus.actorReceive
#[async_trait]
pub trait Todo {
    async fn handle_request(&self, ctx: &Context, arg: &HttpRequest) -> RpcResult<HttpResponse>;
}

/// TodoReceiver receives messages defined in the Todo service trait
/// Description of Todo service
#[doc(hidden)]
#[async_trait]
pub trait TodoReceiver: MessageDispatch + Todo {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "HandleRequest" => {
                let value: HttpRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'HttpRequest': {}", e)))?;

                let resp = Todo::handle_request(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Todo::{}",
                message.method
            ))),
        }
    }
}

/// TodoSender sends messages to a Todo service
/// Description of Todo service
/// client for sending Todo messages
#[derive(Debug)]
pub struct TodoSender<T: Transport> {
    transport: T,
}

impl<T: Transport> TodoSender<T> {
    /// Constructs a TodoSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> TodoSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl TodoSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Todo for TodoSender<T> {
    #[allow(unused)]
    async fn handle_request(&self, ctx: &Context, arg: &HttpRequest) -> RpcResult<HttpResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Todo.HandleRequest",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: HttpResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': HttpResponse", e)))?;
        Ok(value)
    }
}
