// This file is @generated by wasmcloud/weld-codegen 0.6.0.
// It is not intended for manual editing.
// namespace: org.wasmcloud.interface.todo.todo

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// Description of Todo service
/// wasmbus.actorReceive
#[async_trait]
pub trait Todo {
    async fn handle_request(
        &self,
        ctx: &Context,
        arg: &wasmcloud_interface_httpserver::HttpRequest,
    ) -> RpcResult<wasmcloud_interface_httpserver::HttpResponse>;
}

/// TodoReceiver receives messages defined in the Todo service trait
/// Description of Todo service
#[doc(hidden)]
#[async_trait]
pub trait TodoReceiver: MessageDispatch + Todo {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "HandleRequest" => {
                let value: wasmcloud_interface_httpserver::HttpRequest =
                    wasmbus_rpc::common::deserialize(&message.arg)
                        .map_err(|e| RpcError::Deser(format!("'HttpRequest': {}", e)))?;

                let resp = Todo::handle_request(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Todo::{}",
                message.method
            ))),
        }
    }
}

/// TodoSender sends messages to a Todo service
/// Description of Todo service
/// client for sending Todo messages
#[derive(Debug)]
pub struct TodoSender<T: Transport> {
    transport: T,
}

impl<T: Transport> TodoSender<T> {
    /// Constructs a TodoSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> TodoSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl TodoSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Todo for TodoSender<T> {
    #[allow(unused)]
    async fn handle_request(
        &self,
        ctx: &Context,
        arg: &wasmcloud_interface_httpserver::HttpRequest,
    ) -> RpcResult<wasmcloud_interface_httpserver::HttpResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Todo.HandleRequest",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: wasmcloud_interface_httpserver::HttpResponse =
            wasmbus_rpc::common::deserialize(&resp)
                .map_err(|e| RpcError::Deser(format!("'{}': HttpResponse", e)))?;
        Ok(value)
    }
}
